--- 
apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
  name: nginx-rs
spec: 
  replicas: 3
  selector: 
   matchLabels:   
     app: nginx
  template: 
   metadata: 
    labels: 
      app: nginx
    name: nginx-pod
   spec: 
    containers: 
      - 
        image: nginx
        name: nginx-container
        ports: 
          - 
            containerPort: 80
